// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redirect_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUrlGetter creates a new instance of MockUrlGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlGetter {
	mock := &MockUrlGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUrlGetter is an autogenerated mock type for the UrlGetter type
type MockUrlGetter struct {
	mock.Mock
}

type MockUrlGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlGetter) EXPECT() *MockUrlGetter_Expecter {
	return &MockUrlGetter_Expecter{mock: &_m.Mock}
}

// GetURL provides a mock function for the type MockUrlGetter
func (_mock *MockUrlGetter) GetURL(ctx context.Context, alias string) (string, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for GetURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlGetter_GetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetURL'
type MockUrlGetter_GetURL_Call struct {
	*mock.Call
}

// GetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockUrlGetter_Expecter) GetURL(ctx interface{}, alias interface{}) *MockUrlGetter_GetURL_Call {
	return &MockUrlGetter_GetURL_Call{Call: _e.mock.On("GetURL", ctx, alias)}
}

func (_c *MockUrlGetter_GetURL_Call) Run(run func(ctx context.Context, alias string)) *MockUrlGetter_GetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlGetter_GetURL_Call) Return(s string, err error) *MockUrlGetter_GetURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUrlGetter_GetURL_Call) RunAndReturn(run func(ctx context.Context, alias string) (string, error)) *MockUrlGetter_GetURL_Call {
	_c.Call.Return(run)
	return _c
}
