// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package save_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAliasGenerator creates a new instance of MockAliasGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAliasGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAliasGenerator {
	mock := &MockAliasGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAliasGenerator is an autogenerated mock type for the AliasGenerator type
type MockAliasGenerator struct {
	mock.Mock
}

type MockAliasGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAliasGenerator) EXPECT() *MockAliasGenerator_Expecter {
	return &MockAliasGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type MockAliasGenerator
func (_mock *MockAliasGenerator) Generate() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAliasGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockAliasGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
func (_e *MockAliasGenerator_Expecter) Generate() *MockAliasGenerator_Generate_Call {
	return &MockAliasGenerator_Generate_Call{Call: _e.mock.On("Generate")}
}

func (_c *MockAliasGenerator_Generate_Call) Run(run func()) *MockAliasGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAliasGenerator_Generate_Call) Return(s string) *MockAliasGenerator_Generate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAliasGenerator_Generate_Call) RunAndReturn(run func() string) *MockAliasGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
