// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package save_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUrlSaver creates a new instance of MockUrlSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlSaver {
	mock := &MockUrlSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUrlSaver is an autogenerated mock type for the UrlSaver type
type MockUrlSaver struct {
	mock.Mock
}

type MockUrlSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlSaver) EXPECT() *MockUrlSaver_Expecter {
	return &MockUrlSaver_Expecter{mock: &_m.Mock}
}

// SaveURL provides a mock function for the type MockUrlSaver
func (_mock *MockUrlSaver) SaveURL(ctx context.Context, originalURL string, alias string) error {
	ret := _mock.Called(ctx, originalURL, alias)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, originalURL, alias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUrlSaver_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type MockUrlSaver_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
//   - alias string
func (_e *MockUrlSaver_Expecter) SaveURL(ctx interface{}, originalURL interface{}, alias interface{}) *MockUrlSaver_SaveURL_Call {
	return &MockUrlSaver_SaveURL_Call{Call: _e.mock.On("SaveURL", ctx, originalURL, alias)}
}

func (_c *MockUrlSaver_SaveURL_Call) Run(run func(ctx context.Context, originalURL string, alias string)) *MockUrlSaver_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUrlSaver_SaveURL_Call) Return(err error) *MockUrlSaver_SaveURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUrlSaver_SaveURL_Call) RunAndReturn(run func(ctx context.Context, originalURL string, alias string) error) *MockUrlSaver_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}
