// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package erase_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUrlEraser creates a new instance of MockUrlEraser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlEraser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlEraser {
	mock := &MockUrlEraser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUrlEraser is an autogenerated mock type for the UrlEraser type
type MockUrlEraser struct {
	mock.Mock
}

type MockUrlEraser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlEraser) EXPECT() *MockUrlEraser_Expecter {
	return &MockUrlEraser_Expecter{mock: &_m.Mock}
}

// DeleteURL provides a mock function for the type MockUrlEraser
func (_mock *MockUrlEraser) DeleteURL(ctx context.Context, alias string) (string, error) {
	ret := _mock.Called(ctx, alias)

	if len(ret) == 0 {
		panic("no return value specified for DeleteURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, alias)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, alias)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, alias)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlEraser_DeleteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteURL'
type MockUrlEraser_DeleteURL_Call struct {
	*mock.Call
}

// DeleteURL is a helper method to define mock.On call
//   - ctx context.Context
//   - alias string
func (_e *MockUrlEraser_Expecter) DeleteURL(ctx interface{}, alias interface{}) *MockUrlEraser_DeleteURL_Call {
	return &MockUrlEraser_DeleteURL_Call{Call: _e.mock.On("DeleteURL", ctx, alias)}
}

func (_c *MockUrlEraser_DeleteURL_Call) Run(run func(ctx context.Context, alias string)) *MockUrlEraser_DeleteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlEraser_DeleteURL_Call) Return(s string, err error) *MockUrlEraser_DeleteURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUrlEraser_DeleteURL_Call) RunAndReturn(run func(ctx context.Context, alias string) (string, error)) *MockUrlEraser_DeleteURL_Call {
	_c.Call.Return(run)
	return _c
}
